package interfaceGrafica;


import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author anderson
 */
public class Caixa extends javax.swing.JFrame {

    /**
     * Creates new form Caixa
     */
    public Caixa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        campoCodigo = new javax.swing.JTextField();
        btBuscar = new javax.swing.JButton();
        campoUnt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campoQtd = new javax.swing.JTextField();
        campoTotal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        campoRecebido = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        campoTroco = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btFinalizar = new javax.swing.JButton();
        labelProduto = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btCalcularTroco = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Chilanka", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(69, 193, 70));
        jLabel1.setText("CAIXA LIVRE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 12, -1, -1));
        getContentPane().add(campoCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 113, -1));

        btBuscar.setText("Buscar");
        btBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btBuscarMouseClicked(evt);
            }
        });
        getContentPane().add(btBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 65, -1, -1));
        getContentPane().add(campoUnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 113, 58));

        jLabel2.setText("Quantidade");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel3.setText("Valor Unitario");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, -1));
        getContentPane().add(campoQtd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 140, 58));
        getContentPane().add(campoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 113, 58));

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        jLabel4.setText("TOTAL");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, -1, -1));

        jLabel5.setText("X");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 16, -1));

        jLabel6.setText("=");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 19, -1));
        getContentPane().add(campoRecebido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 133, 67));

        jLabel7.setText("Valor Recebido");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));
        getContentPane().add(campoTroco, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 113, 67));

        jLabel8.setText("Troco");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, -1, -1));

        btFinalizar.setText("Finalizar");
        btFinalizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btFinalizarMouseClicked(evt);
            }
        });
        getContentPane().add(btFinalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 350, 113, -1));

        labelProduto.setText("Produto");
        getContentPane().add(labelProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 290, -1));

        jButton1.setText("Calcular");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, -1, -1));

        btCalcularTroco.setText("Calcular");
        btCalcularTroco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCalcularTrocoMouseClicked(evt);
            }
        });
        getContentPane().add(btCalcularTroco, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, -1, -1));

        jButton2.setText("<-");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        btExcluir.setText("Limpar");
        btExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btExcluirMouseClicked(evt);
            }
        });
        getContentPane().add(btExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btBuscarMouseClicked
        
//        Passar para inteiro um determinado texto
        int codigo = Integer.parseInt(campoCodigo.getText());

        switch (codigo) {

            case 101:
                System.out.println("Cachorro quente");
                labelProduto.setText("Cachorro quente");
                campoUnt.setText("2.50");
                break;
            case 102:
                System.out.println("Pitchula");
                labelProduto.setText("Pitchula");
                campoUnt.setText("1.00");
                break;
            case 103:
                System.out.println("Pastel");
                labelProduto.setText("Pastel");
                campoUnt.setText("3.00");
                break;
            default:
                System.out.println("Produto nao cadastrado");
                labelProduto.setText("Produto nao encontrado");

        }
        
        
    }//GEN-LAST:event_btBuscarMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        
        double quantidade = Double.parseDouble(campoQtd.getText());
        
        double valorUnt = Double.parseDouble(campoUnt.getText());
        
        campoTotal.setText(""+quantidade * valorUnt);
    }//GEN-LAST:event_jButton1MouseClicked

    private void btCalcularTrocoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCalcularTrocoMouseClicked
        // TODO add your handling code here:
        
        double valorRecebido = Double.parseDouble(campoRecebido.getText());
        
        double valorTotal =  Double.parseDouble(campoTotal.getText());
        
        if (valorRecebido >= valorTotal){
            double resultado = valorRecebido - valorTotal;
            campoTroco.setText("" + resultado);
        } else {
            
            JOptionPane.showMessageDialog(null, "Valor abaixo do total");
        }
    }//GEN-LAST:event_btCalcularTrocoMouseClicked

    private void btFinalizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btFinalizarMouseClicked
        // TODO add your handling code here:
        
       limpar();
    }//GEN-LAST:event_btFinalizarMouseClicked

    
    public void limpar() {
     campoCodigo.setText("");
        campoQtd.setText("");
        campoRecebido.setText("");
        campoTotal.setText("");
        campoTroco.setText("");
        campoUnt.setText("");
        labelProduto.setText("Produto");
        btExcluir.setText("tal");
    }
    
    
    
    
    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        
                
//        Fechar a tela atual
        dispose();
        
//        Abrir a tela de login
        Login l = new Login();
        l.setVisible(true);

    }//GEN-LAST:event_jButton2MouseClicked

    private void btExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btExcluirMouseClicked
        // TODO add your handling code here:
        
        limpar();
    }//GEN-LAST:event_btExcluirMouseClicked

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // TODO add your handling code here:
        System.out.println("Pressionado");
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
        System.out.println("Teste");
    }//GEN-LAST:event_jButton1MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Caixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Caixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Caixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Caixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Caixa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btCalcularTroco;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btFinalizar;
    private javax.swing.JTextField campoCodigo;
    private javax.swing.JTextField campoQtd;
    private javax.swing.JTextField campoRecebido;
    private javax.swing.JTextField campoTotal;
    private javax.swing.JTextField campoTroco;
    private javax.swing.JTextField campoUnt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel labelProduto;
    // End of variables declaration//GEN-END:variables
}
